---
- name: Install required packages
  loop:
    - "{{ 'plocate' if ansible_facts['distribution_version'] is version('22.04', '>') else 'mlocate' }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: "{{ mlocate_state }}"
  tags:
    - mlocate

...
